title:              "Mia Planet"
tagline:            "취미 탐방기"
email:              "younghyunryu33@gmail.com"
description:        "차와 추리물을 찾아 탐방하는 유유자적 취미생활 라이프"
author:             "Mia"
baseurl:            "/"
url:                "https://mangorany.github.io/"
locale:             "ko_KR"
thumbnail:          "img/home.png"
# 블로그 disqus shortname
disqus:
shortname: mangorany

# Social Profiles
instagram_username: instagram_mia._.planet
facebook_username:  facebook_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
